// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6d1OmiZfgIygVlZtJG2EpRIXnn_KIb4',
    appId: '1:265029089097:web:1a0729fd89e7740bbc0c98',
    messagingSenderId: '265029089097',
    projectId: 'todolistapp-b8931',
    authDomain: 'todolistapp-b8931.firebaseapp.com',
    storageBucket: 'todolistapp-b8931.firebasestorage.app',
    measurementId: 'G-SCEH1TJM9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbqj_jDIBvY6sQW7tZyf4rt_DfwIAE_iY',
    appId: '1:265029089097:android:36dd2406e078487dbc0c98',
    messagingSenderId: '265029089097',
    projectId: 'todolistapp-b8931',
    storageBucket: 'todolistapp-b8931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqo2RInOdwsTQ92PJRVmizUrBtAgzUy3M',
    appId: '1:265029089097:ios:8cfe16acee7ab5c1bc0c98',
    messagingSenderId: '265029089097',
    projectId: 'todolistapp-b8931',
    storageBucket: 'todolistapp-b8931.firebasestorage.app',
    iosBundleId: 'com.example.todolistfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqo2RInOdwsTQ92PJRVmizUrBtAgzUy3M',
    appId: '1:265029089097:ios:8cfe16acee7ab5c1bc0c98',
    messagingSenderId: '265029089097',
    projectId: 'todolistapp-b8931',
    storageBucket: 'todolistapp-b8931.firebasestorage.app',
    iosBundleId: 'com.example.todolistfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS6d1OmiZfgIygVlZtJG2EpRIXnn_KIb4',
    appId: '1:265029089097:web:a55217bb41358deabc0c98',
    messagingSenderId: '265029089097',
    projectId: 'todolistapp-b8931',
    authDomain: 'todolistapp-b8931.firebaseapp.com',
    storageBucket: 'todolistapp-b8931.firebasestorage.app',
    measurementId: 'G-TS7PWEL9XN',
  );
}
